language: java

git:
  submodules: false

jdk:
  - openjdk8

install:
  - ant clean

script:
  - ant compile

after_success:
  - ant jar
  - "./.travis/javadoc_update.sh"
env:
  global:
    secure: "Tei0vpFdZ1h9Nc5NtvFAKy9cJfi58u/bPx220kCDqET4WfCgM0pIt6wrZCmu8TIVcwWiXZCrpS6fYhaq4MBw+1u5NtvjXDQHblQ6rThD2sjPqkSj/C/Eo0zWnid48mM8KyPoQPCWTne3RUMgNwqDlCOPQW7ZHu34nNyCU1JgpmUzgaC67gaUwDi0K4NVclRNUqpHEXw36TJx0qysNlQZPMlNaM/uyi7qzjm30TSPT3XnpmMvsrnxZEiif4wcrLm1fNQdweDr+NGqqf4q8N7EER4dlmJvacjPKhSeLOMhHDijJ6+EnUy2V7t1BZcGsSdFp44J9wKaeRc6yNdGY2WdfGmfCBexoYq6+XFUnfX8TgWGGHcxD1FIxd4sABQxcbzPgIZLFdCDzoLXzpPvj+dTYfNCXVIM0Blo0249Ds2xWSgVfxR5Mna7WllGHYxeCp6mer+K53juFOY+4LwrO0sG5Ps0GtiCNjDt8t+1MbR1NOSvymaePDEmHiGoVjA8EnO/lksIrXerjTwpnf/JPB0dndsvESIt3KYYKiSWaOHEYV9bok3/NExGoDFo4TENot1TVcKWR+eq7BFHWZfDs3AGY/v2ev6f8bLpUzLnzuqcTq5iU7g5k5XOZpwjl0/Z01NyPaTdVtSBjTKwTf1XDVs8XnVeEMBJlWDQds8aa8cbw5I="
